- name: Add Redis Repo into source list
  yum:
    name: epel-release
    state: present

- name: Install Redis
  yum:
    name: redis
    state: present

- name: Configuring Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: restart redis

- name: Flush handlers
  meta: flush_handlers
