---
# compute-video-demo-ansible
- name: Create Compute Engine instances
  hosts: local
  gather_facts: False
  vars_files:
    - gcp_vars/secrets/auth.yml
    - gcp_vars/machines.yml
    - gcp_vars/zone.yml
  tasks:
    - name: Bring up the instances in the data zone
      gce:
        instance_names: "{{ names_zonea }}"
        machine_type: "{{ machine_type }}"
        image: "{{ image }}"
        zone: "{{ zonea }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      register: gcea
  post_tasks:
    - name: Wait for SSH for instances in data zone
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ gcea.instance_data }}"
    - name: Save host data for data zone
      add_host: hostname={{ item.public_ip }} groupname=gce_instances_ips
      with_items: "{{ gcea.instance_data }}"